### ISSUE TITLE
SubmitUrl only encrypted for GetLogins, not for CreateLogin

### ISSUE THREAD

**Issue by Doccrazy** [vladimiry/keepasshttp-client#2]
Currently CreateLogin.SubmitUrl is transmitted as plain text. But according to the server implementation, this value should be encrypted like in GetLogins:
https://github.com/pfn/keepasshttp/blob/b9a6813bfc9ccc9618938249c1bfff744a28ca44/KeePassHttp/Handlers.cs#L795
https://github.com/pfn/keepasshttp/blob/b9a6813bfc9ccc9618938249c1bfff744a28ca44/KeePassHttp/Protocol.cs#L98

**Comment by vladimiry** [comment]
Just published v2.2.8 has got the fix.
